### PR TITLE
Add triggerable_events to list events available from current state

### PR DESCRIPTION
**Pull request by nathanl**
As discussed in https://github.com/soveran/micromachine/issues/36

### CODE REVIEW

**Comment by soveran** [comment]
In the example for the README it says `triggerable` instead of `triggerable_events`. We hadn't considered using just `triggerable`, but it looks good too. Which one do you prefer? I like both, so up to you!

**Comment by nathanl** [comment]
Whoops, meant to say `triggerable_events` - just a typing mistake. :)

**Comment by nathanl** [comment]
@soveran I amended the commit to fix the inconsistency.

**Comment by soveran** [comment]
@nathanl Excellent, thanks a lot!

**Pull request merged**
